# Funding Configuration
# Obsidian Cursor - Miyabi Autonomous Development Framework

# GitHub Sponsors
# github: [your-github-username]

# Open Collective
# open_collective: obsidian-cursor

# Ko-fi
# ko_fi: your-kofi-username

# Patreon
# patreon: your-patreon-username

# Custom URLs
# custom: ['https://your-custom-url.com']

# Note: Uncomment and configure the funding platforms you want to use
# For now, this project is maintained as open-source without funding requirements
